---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-monitoring-agent
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: b0a00765-ee91-4c2a-87fc-df46dbc58cdb
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-deploy-base-ocp-and-monitoring-instances.sh"
        post_validation: "tests/scripts/post-validation-deploy-base-ocp-and-monitoring-instances.sh"
